import { defineAppConfig } from '@elyvel/core'
import { EloquentServiceProvider } from '@elyvel/database'
import { I18nServiceProvider } from '@elyvel/i18n'
import { AppServiceProvider } from '../app/providers/AppServiceProvider'

/**
 * Application config. `defineAppConfig` pins the type, so your editor
 * autocompletes every option and typos fail the type-check.
 *
 * Cache/Mail/Notification/Queue/Schedule providers are no longer listed here —
 * `elyvel package:discover` picks them up automatically (see
 * bootstrap/providers.generated.ts, regenerated by `bun install`'s
 * postinstall). Database/i18n stay explicit: they're mandatory-core, not
 * optional add-on packages, matching Laravel's own convention of never
 * auto-discovering its own framework providers.
 */
export default defineAppConfig({
  name: process.env.APP_NAME ?? 'Worker Console',
  env: process.env.APP_ENV ?? 'local',
  key: process.env.APP_KEY, // secret for `encrypted` model casts (AES-256-GCM)
  port: Number(process.env.PORT ?? 3000),

  providers: [
    EloquentServiceProvider,
    I18nServiceProvider,
    AppServiceProvider,
  ],
})
