import { defineAppConfig } from '@elyvel/core'
import { EloquentServiceProvider } from '@elyvel/database'
import { I18nServiceProvider } from '@elyvel/i18n'
import { AppServiceProvider } from '../app/providers/AppServiceProvider'
import { EventServiceProvider } from '../app/providers/EventServiceProvider'
import { ScheduleServiceProvider } from '../app/providers/ScheduleServiceProvider'

/**
 * Application config. `defineAppConfig` pins the type, so your editor
 * autocompletes every option and typos fail the type-check.
 *
 * Auth/Mail/Cache/Storage/Queue/Broadcast/Notification providers are no
 * longer listed here — `elyvel package:discover` picks them up automatically
 * (see bootstrap/providers.generated.ts, regenerated by `bun install`'s
 * postinstall). Database/i18n stay explicit (mandatory-core, not opt-in).
 * Event/ScheduleServiceProvider stay explicit too — these are THIS app's own
 * subclasses (registering its listeners/scheduled tasks), not the generic
 * package providers, so auto-discovery doesn't apply to them.
 */
export default defineAppConfig({
  name: process.env.APP_NAME ?? 'Fullstack Vue',
  env: process.env.APP_ENV ?? 'local',
  key: process.env.APP_KEY, // secret for `encrypted` model casts (AES-256-GCM)
  port: Number(process.env.PORT ?? 3000),

  providers: [
    EloquentServiceProvider,
    I18nServiceProvider,
    EventServiceProvider,
    ScheduleServiceProvider,
    AppServiceProvider,
  ],
})
