import type { ServiceProviderClass } from '@elyvel/core'
import { existsSync, readdirSync } from 'node:fs'
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'

interface Discoverable {
  elyvelProviders?: ServiceProviderClass[]
}

interface DiscoveredPackage {
  name: string
  providerNames: string[]
}

async function readDontDiscover(cwd: string): Promise<string[]> {
  const appConfigPath = join(cwd, 'config', 'app.ts')
  if (!existsSync(appConfigPath))
    return []
  const module = (await import(appConfigPath)) as { default?: { dontDiscover?: string[] } }
  return module.default?.dontDiscover ?? []
}

/**
 * `elyvel package:discover` — Laravel's package auto-discovery, adapted to
 * this framework's no-runtime-magic stance: instead of a JSON manifest read
 * at every boot, this generates real, typed, import-checked TypeScript
 * (`bootstrap/providers.generated.ts`). A broken/renamed provider export
 * fails loudly HERE (or at `bun run typecheck`), not silently at request
 * time. Re-run whenever dependencies change — wired into the base template's
 * `postinstall` script so `bun install` keeps it fresh automatically.
 *
 * A package opts in by exporting `elyvelProviders: ServiceProviderClass[]`
 * from its main entry (see e.g. `@elyvel/auth`'s `src/index.ts`) — a real
 * code export, not `package.json` metadata, so it can't drift from what the
 * package actually ships. An app opts a package OUT via `dontDiscover` in
 * `config/app.ts`.
 */
export async function packageDiscoverCommand(): Promise<number> {
  const cwd = process.cwd()
  const scopeDir = join(cwd, 'node_modules', '@elyvel')
  if (!existsSync(scopeDir)) {
    console.log('No @elyvel/* packages installed — nothing to discover.')
    return 0
  }

  const dontDiscover = new Set(await readDontDiscover(cwd))
  const packageNames = readdirSync(scopeDir, { withFileTypes: true })
    .filter(entry => entry.isDirectory() || entry.isSymbolicLink())
    .map(entry => `@elyvel/${entry.name}`)
    .filter(name => name !== '@elyvel/cli' && !dontDiscover.has(name))

  const discovered: DiscoveredPackage[] = []
  for (const name of packageNames) {
    let module: Discoverable
    try {
      // Resolve relative to the TARGET app's directory, not this CLI source
      // file's own location — a bare `import(name)` here would resolve
      // against @elyvel/cli's own dependency graph instead of the app's.
      const resolved = Bun.resolveSync(name, cwd)
      module = (await import(resolved)) as Discoverable
    }
    catch (error) {
      console.error(`✗ Failed to import "${name}" during discovery: ${error instanceof Error ? error.message : String(error)}`)
      return 1
    }
    if (!module.elyvelProviders || module.elyvelProviders.length === 0)
      continue
    discovered.push({ name, providerNames: module.elyvelProviders.map(p => p.name) })
  }

  const manifestPath = join(cwd, 'bootstrap', 'providers.generated.ts')
  await mkdir(dirname(manifestPath), { recursive: true })

  if (discovered.length === 0) {
    await writeFile(
      manifestPath,
      `// AUTO-GENERATED by \`elyvel package:discover\` — do not edit by hand.\n`
      + `// No discoverable packages found.\n`
      + `export const discoveredProviders = []\n`,
    )
    console.log('No discoverable providers found.')
    return 0
  }

  const imports = discovered
    .map(pkg => `import { ${pkg.providerNames.join(', ')} } from '${pkg.name}'`)
    .join('\n')
  const list = discovered.flatMap(pkg => pkg.providerNames).join(', ')

  await writeFile(
    manifestPath,
    `// AUTO-GENERATED by \`elyvel package:discover\` — do not edit by hand.\n`
    + `// Regenerate after changing dependencies (also runs on \`bun install\` via postinstall).\n`
    + `${imports}\n\n`
    + `export const discoveredProviders = [${list}]\n`,
  )

  console.log(`Discovered ${discovered.length} package(s):`)
  for (const pkg of discovered)
    console.log(`  ${pkg.name} → ${pkg.providerNames.join(', ')}`)
  if (dontDiscover.size > 0)
    console.log(`Excluded (dontDiscover): ${[...dontDiscover].join(', ')}`)

  return 0
}
