import type { ConsoleCommand, ServiceProviderClass } from '@elyvel/core'
import { existsSync, readdirSync } from 'node:fs'
import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { error, line } from '../io'

interface Discoverable {
  elyvelProviders?: ServiceProviderClass[]
}

interface CommandsModule {
  elyvelCommands?: ConsoleCommand[]
}

interface DiscoveredPackage {
  name: string
  providerNames: string[]
  hasCommands: boolean
}

/** Whether `error` is Bun's "no such module" resolution failure, as opposed to a real bug in a module that DID resolve. */
function isModuleNotFoundError(error: unknown): boolean {
  return typeof error === 'object' && error !== null && 'code' in error
    && (error as { code?: unknown }).code === 'ERR_MODULE_NOT_FOUND'
}

async function readDontDiscover(cwd: string): Promise<string[]> {
  const appConfigPath = join(cwd, 'config', 'app.ts')
  if (!existsSync(appConfigPath))
    return []
  const module = (await import(appConfigPath)) as { default?: { dontDiscover?: string[] } }
  return module.default?.dontDiscover ?? []
}

async function writeProvidersManifest(cwd: string, discovered: DiscoveredPackage[]): Promise<string> {
  const manifestPath = join(cwd, 'bootstrap', 'providers.generated.ts')
  const withProviders = discovered.filter(pkg => pkg.providerNames.length > 0)

  if (withProviders.length === 0) {
    await writeFile(
      manifestPath,
      `// AUTO-GENERATED by \`elyvel package:discover\` — do not edit by hand.\n`
      + `// No discoverable packages found.\n`
      + `export const discoveredProviders = []\n`,
    )
    return manifestPath
  }

  const imports = withProviders
    .map(pkg => `import { ${pkg.providerNames.join(', ')} } from '${pkg.name}'`)
    .join('\n')
  const list = withProviders.flatMap(pkg => pkg.providerNames).join(', ')

  await writeFile(
    manifestPath,
    `// AUTO-GENERATED by \`elyvel package:discover\` — do not edit by hand.\n`
    + `// Regenerate after changing dependencies (also runs on \`bun install\` via postinstall).\n`
    + `${imports}\n\n`
    + `export const discoveredProviders = [${list}]\n`,
  )
  return manifestPath
}

/**
 * Companion manifest to `providers.generated.ts`, read by `@elyvel/cli`
 * itself (not the running app) so it can dispatch a package's own
 * `elyvel <pkg>:<command>` without depending on that package at all — see
 * `ConsoleCommand`/`elyvelCommands`.
 */
async function writeCommandsManifest(cwd: string, discovered: DiscoveredPackage[]): Promise<string> {
  const manifestPath = join(cwd, 'bootstrap', 'commands.generated.ts')
  const withCommands = discovered.filter(pkg => pkg.hasCommands)

  if (withCommands.length === 0) {
    await writeFile(
      manifestPath,
      `// AUTO-GENERATED by \`elyvel package:discover\` — do not edit by hand.\n`
      + `// No packages exporting elyvelCommands were found.\n`
      + `export const discoveredCommands = []\n`,
    )
    return manifestPath
  }

  const imports = withCommands
    .map((pkg, i) => `import { elyvelCommands as commands$${i} } from '${pkg.name}/cli'`)
    .join('\n')
  const list = withCommands.map((_pkg, i) => `...commands$${i}`).join(', ')

  await writeFile(
    manifestPath,
    `// AUTO-GENERATED by \`elyvel package:discover\` — do not edit by hand.\n`
    + `// Regenerate after changing dependencies (also runs on \`bun install\` via postinstall).\n`
    + `${imports}\n\n`
    + `export const discoveredCommands = [${list}]\n`,
  )
  return manifestPath
}

/**
 * `elyvel package:discover` — Laravel's package auto-discovery, adapted to
 * this framework's no-runtime-magic stance: instead of a JSON manifest read
 * at every boot, this generates real, typed, import-checked TypeScript
 * (`bootstrap/providers.generated.ts` + `bootstrap/commands.generated.ts`).
 * A broken/renamed export fails loudly HERE (or at `bun run typecheck`), not
 * silently at request/CLI-dispatch time. Re-run whenever dependencies
 * change — wired into the base template's `postinstall` script so
 * `bun install` keeps both fresh automatically.
 *
 * A package opts in by exporting `elyvelProviders: ServiceProviderClass[]`
 * from its main entry (see e.g. `@elyvel/auth`'s `src/index.ts`) and/or
 * `elyvelCommands: ConsoleCommand[]` from a SEPARATE `<pkg>/cli` subpath
 * export (see e.g. `@elyvel/queue`'s `package.json` `exports` + its
 * `src/cli.ts`) — real code exports, not `package.json` metadata alone, so
 * they can't drift from what the package actually ships. Commands live
 * behind their own subpath (not the main entry) specifically so a running
 * app importing `@elyvel/queue` for `dispatch()`/`Job` etc. never pulls
 * `queueWorkCommand` and friends into its own process — only this
 * discovery step (and the separate `elyvel` CLI process dispatching a
 * discovered command) ever imports `<pkg>/cli`. This is also what keeps
 * `@elyvel/cli` itself from needing to depend on `@elyvel/queue`,
 * `@elyvel/database`, etc. just to know their commands exist — any package,
 * including a third-party one, can add its own `elyvel <name>:<command>`
 * this way. An app opts a package OUT of both via `dontDiscover` in
 * `config/app.ts`.
 */
export async function packageDiscoverCommand(): Promise<number> {
  const cwd = process.cwd()
  const scopeDir = join(cwd, 'node_modules', '@elyvel')
  if (!existsSync(scopeDir)) {
    line('No @elyvel/* packages installed — nothing to discover.')
    return 0
  }

  const dontDiscover = new Set(await readDontDiscover(cwd))
  const packageNames = readdirSync(scopeDir, { withFileTypes: true })
    .filter(entry => entry.isDirectory() || entry.isSymbolicLink())
    .map(entry => `@elyvel/${entry.name}`)
    .filter(name => name !== '@elyvel/cli' && !dontDiscover.has(name))

  const discovered: DiscoveredPackage[] = []
  for (const name of packageNames) {
    let module: Discoverable
    try {
      // Resolve relative to the TARGET app's directory, not this CLI source
      // file's own location — a bare `import(name)` here would resolve
      // against @elyvel/cli's own dependency graph instead of the app's.
      const resolved = Bun.resolveSync(name, cwd)
      module = (await import(resolved)) as Discoverable
    }
    catch (err) {
      error(`✗ Failed to import "${name}" during discovery: ${err instanceof Error ? err.message : String(err)}`)
      return 1
    }
    const providerNames = module.elyvelProviders?.map(p => p.name) ?? []

    // Commands live behind a SEPARATE `<pkg>/cli` subpath (not the main
    // entry above), so a running app never loads them — see the doc
    // comment on `packageDiscoverCommand`. A package simply not declaring
    // that subpath is the common case, not an error; only a subpath that
    // resolves but then fails to import (a real bug in that file) is fatal.
    let hasCommands = false
    try {
      const resolvedCli = Bun.resolveSync(`${name}/cli`, cwd)
      const cliModule = (await import(resolvedCli)) as CommandsModule
      hasCommands = Boolean(cliModule.elyvelCommands && cliModule.elyvelCommands.length > 0)
    }
    catch (err) {
      if (isModuleNotFoundError(err)) {
        hasCommands = false
      }
      else {
        error(`✗ Failed to import "${name}/cli" during discovery: ${err instanceof Error ? err.message : String(err)}`)
        return 1
      }
    }

    if (providerNames.length === 0 && !hasCommands)
      continue
    discovered.push({ name, providerNames, hasCommands })
  }

  await mkdir(join(cwd, 'bootstrap'), { recursive: true })
  await writeProvidersManifest(cwd, discovered)
  await writeCommandsManifest(cwd, discovered)

  if (discovered.length === 0) {
    line('No discoverable providers or commands found.')
    return 0
  }

  line(`Discovered ${discovered.length} package(s):`)
  for (const pkg of discovered) {
    const bits = [
      pkg.providerNames.length > 0 ? pkg.providerNames.join(', ') : null,
      pkg.hasCommands ? 'commands' : null,
    ].filter(Boolean)
    line(`  ${pkg.name} → ${bits.join(' + ')}`)
  }
  if (dontDiscover.size > 0)
    line(`Excluded (dontDiscover): ${[...dontDiscover].join(', ')}`)

  return 0
}
