import type { Connection } from './connection'
import { existsSync, mkdirSync, readdirSync, rmSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'

/** Where a dump lands by default, mirroring Laravel's `database/schema/`. */
export function defaultDumpPath(connectionName = 'default', base = process.cwd()): string {
  return resolve(base, 'database', 'schema', `${connectionName}-schema.sql`)
}

const MIGRATIONS_TABLE = '_elyvel_migrations'
/**
 * The migration mutex is transient infrastructure, not schema. Dumping it meant a
 * restore recreated a lock table the migrator then tried to create again, failing
 * with "table already exists" — so the dump could never be loaded.
 */
const LOCK_TABLE = '_elyvel_migrations_lock'

/**
 * Dump the database's CURRENT structure to one SQL file — Laravel's
 * `schema:dump`. Once a project has hundreds of migrations, replaying them from
 * scratch (in CI, or for a new developer) is slow and increasingly fragile; the
 * dump is loaded in one shot instead and only migrations added *after* it are
 * replayed.
 *
 * The applied-migration rows are dumped alongside the structure, so a database
 * restored from the file already knows which migrations it contains and won't try
 * to re-run them.
 */
export async function dumpSchema(
  connection: Connection,
  path: string,
): Promise<{ path: string, bytes: number }> {
  const sql = connection.dialect === 'sqlite'
    ? await dumpSqlite(connection)
    : await dumpViaExternalTool(connection)

  mkdirSync(dirname(path), { recursive: true })
  const applied = await appliedRows(connection)
  const body = `${header(connection)}${sql}\n${applied}`
  await Bun.write(path, body)
  return { path, bytes: body.length }
}

function header(connection: Connection): string {
  return [
    '-- elyvel schema dump',
    `-- dialect: ${connection.dialect}`,
    '-- Generated by `elyvel schema:dump`. Load it with `elyvel migrate` on an',
    '-- empty database; migrations added after the dump still run normally.',
    '',
    '',
  ].join('\n')
}

/**
 * SQLite keeps every object's original DDL in `sqlite_master`, so the dump is
 * exact and needs no external binary.
 */
async function dumpSqlite(connection: Connection): Promise<string> {
  const rows = await connection.select<{ sql: string | null, type: string, name: string }>(
    `SELECT type, name, sql FROM sqlite_master
     WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' AND name <> ?
     ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 ELSE 2 END, name`,
    [LOCK_TABLE],
  )
  return rows
    .filter(row => row.sql)
    .map(row => `${row.sql};`)
    .join('\n\n')
}

/**
 * Postgres and MySQL have no in-database source of their own DDL, so — exactly as
 * Laravel does — we shell out to the vendor tool. Failing loudly with the reason
 * beats writing a half-complete dump that only shows up as a broken restore.
 */
async function dumpViaExternalTool(connection: Connection): Promise<string> {
  const isPg = connection.dialect === 'pg'
  const tool = isPg ? 'pg_dump' : 'mysqldump'
  const url = process.env.DATABASE_URL
  if (!url) {
    throw new Error(
      `[eloquent] schema:dump needs DATABASE_URL set for the ${connection.dialect} `
      + `driver: the structure is read with \`${tool}\`, which connects on its own.`,
    )
  }
  const args = isPg
    ? ['--schema-only', '--no-owner', '--no-privileges', url]
    : ['--no-data', '--skip-comments', `--result-file=/dev/stdout`, url]

  const proc = Bun.spawn([tool, ...args], { stdout: 'pipe', stderr: 'pipe' })
  const [out, err, code] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ])
  if (code !== 0) {
    throw new Error(
      `[eloquent] \`${tool}\` exited ${code}: ${err.trim() || '(no output)'}. `
      + `It must be installed and on PATH for schema:dump on ${connection.dialect}.`,
    )
  }
  return out.trim()
}

/** The applied-migration rows, as INSERTs, so a restored database knows its history. */
async function appliedRows(connection: Connection): Promise<string> {
  const rows = await selectLedger(connection)
  if (rows.length === 0)
    return ''
  const values = rows
    .map(row => `  (${quote(row.name)}, ${row.batch}, ${quote(row.ran_at)})`)
    .join(',\n')
  return [
    '',
    '-- Migrations already contained in the structure above.',
    `INSERT INTO ${MIGRATIONS_TABLE} (name, batch, ran_at) VALUES`,
    `${values};`,
    '',
  ].join('\n')
}

interface LedgerRow { name: string, batch: number, ran_at: string }

/**
 * The ledger, or an empty list when the table doesn't exist yet (dumping a
 * database that was built by hand rather than migrated).
 *
 * Only a missing-table error is tolerated. A blanket `.catch(() => [])` here
 * silently swallowed a wrong column name in this very query — the dump looked
 * fine and simply contained no migration history, so a restore would re-run every
 * migration against an already-built schema.
 */
async function selectLedger(connection: Connection): Promise<LedgerRow[]> {
  try {
    return await connection.select<LedgerRow>(
      `SELECT name, batch, ran_at FROM ${MIGRATIONS_TABLE} ORDER BY batch, name`,
    )
  }
  catch (error) {
    if (isMissingTable(error))
      return []
    throw error
  }
}

function isMissingTable(error: unknown): boolean {
  return /no such table|does not exist|doesn't exist|unknown table/i.test(
    error instanceof Error ? error.message : String(error),
  )
}

function quote(value: string): string {
  return `'${value.replace(/'/g, '\'\'')}'`
}

/**
 * Delete the migration files the dump now covers — Laravel's `--prune`.
 *
 * Only files whose migration has actually been APPLIED are removed: pruning a
 * pending migration would erase work the dump doesn't contain. Returns the files
 * removed.
 */
export async function pruneMigrations(connection: Connection, dir: string): Promise<string[]> {
  const applied = new Set(
    (
      await connection
        .select<{ name: string }>(`SELECT name FROM ${MIGRATIONS_TABLE}`)
        .catch(() => [])
    ).map(row => row.name),
  )
  if (applied.size === 0 || !existsSync(dir))
    return []

  const removed: string[] = []
  for (const file of readdirSync(dir).sort()) {
    if (!/\.(?:ts|js)$/.test(file) || file.endsWith('.d.ts'))
      continue
    const name = file.replace(/\.(?:ts|js)$/, '')
    if (!applied.has(name))
      continue
    rmSync(join(dir, file))
    removed.push(file)
  }
  return removed
}

/**
 * Load a dump into an empty database. Called by `migrate` when the migrations
 * table is absent and a dump exists, so a fresh checkout skips replaying history.
 */
export async function loadSchemaDump(connection: Connection, path: string): Promise<boolean> {
  if (!existsSync(path))
    return false
  const sql = await Bun.file(path).text()
  if (!sql.trim())
    return false
  await connection.unprepared(sql)
  return true
}
